Chani0324/Harmony

- build.gradle
- src/main/java/com/sparta/harmony/store/entity/Category.java
- src/main/java/com/sparta/harmony/store/entity/Store.java
- src/main/java/com/sparta/harmony/store/entity/StoreCategory.java
- src/main/java/com/sparta/harmony/user/entity/Role.java
- src/main/java/com/sparta/harmony/user/entity/StoreAddress.java
- src/main/java/com/sparta/harmony/user/entity/User.java
- src/main/java/com/sparta/harmony/user/entity/UserAddress.java
> 식당,카테고리,유저 엔티티 작성

- src/main/java/com/sparta/harmony/review/entity/Review.java
> review entity 생성

- src/main/java/com/sparta/harmony/order/entity/Payments.java
- src/main/java/com/sparta/harmony/user/entity/User.java
user테이블에서 order테이블과 1:N 연관관계 표현
-
연관된 이슈번호: #이슈번호
> user테이블에서 order테이블과 1:N 연관관계 표현

- src/main/java/com/sparta/harmony/order/entity/Order.java
order entity 서비스 메소드에 totalAmount를 구하는 메소드가 자동으로 실행되어 저장이 되도록 설정
-
연관된 이슈번호: #10
> order entity 서비스 메소드에 totalAmount를 구하는 메소드가 자동으로 실행되어 저장이 되도록 설정

- .gitignore
> order test .gitignore 추가

- src/main/java/com/sparta/harmony/order/dto/OrderResponseDto.java
- src/main/java/com/sparta/harmony/order/entity/Order.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- src/main/java/com/sparta/harmony/user/entity/User.java
> user, payments, order entity 연관관계 설정 및 OrderService 코드 리펙토링

- src/main/java/com/sparta/harmony/review/controller/ReviewController.java
- src/main/java/com/sparta/harmony/review/dto/ReviewRequestDto.java
- src/main/java/com/sparta/harmony/review/dto/ReviewResponseDto.java
- src/main/java/com/sparta/harmony/review/entity/Review.java
- src/main/java/com/sparta/harmony/review/repository/ReviewRepository.java
- src/main/java/com/sparta/harmony/review/service/ReviewService.java
> 리뷰 도메인 생성, 조회, 수정, 삭제

- src/main/java/com/sparta/harmony/order/repository/OrderRepository.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
> - 전체 조회 중 소프트 딜리트 적용 안한 값들만 가져오기.

- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/dto/ApiResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderResponseDto.java
- src/main/java/com/sparta/harmony/order/repository/OrderRepository.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
> - 주문id를 통한 상세 주문 조회 + 소프트 딜리트 안된 것 가져오기

- src/main/java/com/sparta/harmony/review/repository/ReviewRepository.java
- src/main/java/com/sparta/harmony/store/controller/CategoryController.java
- src/main/java/com/sparta/harmony/store/controller/StoreController.java
- src/main/java/com/sparta/harmony/store/dto/StoreDetailResponseDto.java
- src/main/java/com/sparta/harmony/store/dto/StoreSearchResponseDto.java
- src/main/java/com/sparta/harmony/store/entity/Store.java
- src/main/java/com/sparta/harmony/store/repository/CategoryRepository.java
- src/main/java/com/sparta/harmony/store/repository/StoreRepository.java
- src/main/java/com/sparta/harmony/store/service/CategoryService.java
- src/main/java/com/sparta/harmony/store/service/StoreService.java
>  음식점, 카테고리 검색 기능

- src/main/java/com/sparta/harmony/order/entity/Order.java
- src/main/java/com/sparta/harmony/order/entity/Payments.java
- src/main/java/com/sparta/harmony/user/entity/User.java
> - user, order, payments 엔티티 간 연관관계 편의 메소드 작성

- src/main/java/com/sparta/harmony/order/handler/exception/OrderExceptionHandler.java
- src/main/java/com/sparta/harmony/order/handler/exception/OrderNotFoundException.java
- src/main/java/com/sparta/harmony/order/handler/exception/PaymentsNotFoundException.java
- src/main/java/com/sparta/harmony/order/handler/exception/RestApiException.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
> - order domain controller 예외 처리 적용

- src/main/java/com/sparta/harmony/review/controller/ReviewController.java
- src/main/java/com/sparta/harmony/review/dto/ReviewRequestDto.java
- src/main/java/com/sparta/harmony/review/dto/ReviewResponseDto.java
- src/main/java/com/sparta/harmony/review/entity/Review.java
- src/main/java/com/sparta/harmony/review/repository/ReviewRepository.java
- src/main/java/com/sparta/harmony/review/service/ReviewService.java
> 리뷰 조회 수정 및 평점 등 요구 사항 일부 반영

- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/dto/OrderResponseDto.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- OrderService 코드 리팩토링
- 주소지 값이 안들어올 시 user에 있는 주소지 정보 사용
- 주문생성 시 주소지 값 추가.
#50
> OrderService 코드 리팩토링 및 기본 주소지 설정

- src/main/java/com/sparta/harmony/order/entity/Order.java
- src/main/java/com/sparta/harmony/order/entity/OrderMenu.java
- src/main/java/com/sparta/harmony/order/entity/Payments.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
> - 엔티티 @DynamicUpdate 적용

- build.gradle
- http/order.http
- src/main/java/com/sparta/harmony/order/config/OpenApiConfig.java
- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/dto/ApiDetailResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/ApiResponsePageDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderDetailResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderResponseOrderMenuListDto.java
- src/main/java/com/sparta/harmony/order/entity/Timestamped.java
- src/main/java/com/sparta/harmony/order/handler/success/SuccessResponseHandler.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- dto 세분화 작업
- swagger gradle 추가
#54
> swagger gradle, dto 세분화 진행

- src/main/java/com/sparta/harmony/review/controller/ReviewController.java
- src/main/java/com/sparta/harmony/review/entity/Review.java
- src/main/java/com/sparta/harmony/review/service/ReviewService.java
- src/main/java/com/sparta/harmony/user/controller/UserController.java
- src/main/java/com/sparta/harmony/user/dto/UserRequestDto.java
- src/main/java/com/sparta/harmony/user/dto/UserResponseDto.java
- src/main/java/com/sparta/harmony/user/entity/User.java
- src/main/java/com/sparta/harmony/user/service/UserService.java
> 리뷰 요구 사항(soft 삭제) 추가 및 유저 crud 구현

- src/main/java/com/sparta/harmony/HarmonyApplication.java
- src/main/java/com/sparta/harmony/review/controller/ReviewController.java
- src/main/java/com/sparta/harmony/review/entity/Review.java
- src/main/java/com/sparta/harmony/review/service/ReviewService.java
- src/main/java/com/sparta/harmony/user/config/SecurityConfig.java
- src/main/java/com/sparta/harmony/user/controller/UserController.java
- src/main/java/com/sparta/harmony/user/dto/UserRequestDto.java
- src/main/java/com/sparta/harmony/user/repository/UserRepository.java
- src/main/java/com/sparta/harmony/user/service/UserService.java
> 유저 요구 사항 적용

- build.gradle
- src/main/java/com/sparta/harmony/order/service/OrderService.java
> - 주문 타입을 TAKEOUT으로 설정시 가게 주소가 주문의 주소에 들어가도록 기능 구현

- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/dto/OrderRequestDto.java
- src/main/java/com/sparta/harmony/order/entity/Order.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
soft delete 조건 추가 및 orderStatus 수정 기능 구현
#63
> soft delete 조건 추가 및 orderStatus 수정 기능 구현

- src/main/java/com/sparta/harmony/common/config/JpaConfig.java
- src/main/java/com/sparta/harmony/common/config/OpenApiConfig.java
- src/main/java/com/sparta/harmony/common/config/QuerydslConfig.java
- src/main/java/com/sparta/harmony/common/dto/ApiResponseDto.java
- src/main/java/com/sparta/harmony/common/dto/ApiResponsePageDto.java
- src/main/java/com/sparta/harmony/common/handler/exception/GlobalExceptionHandler.java
- src/main/java/com/sparta/harmony/common/handler/exception/RestApiException.java
- src/main/java/com/sparta/harmony/common/handler/success/SuccessResponseHandler.java
- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/controller/PaymentsController.java
- src/main/java/com/sparta/harmony/order/dto/OrderDetailResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderMenuListRequestDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderMenuListResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderRequestDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderStatusRequestDto.java
- src/main/java/com/sparta/harmony/order/dto/PaymentsDetailResponseDto.java
- src/main/java/com/sparta/harmony/order/exception/OrderNotFoundException.java
- src/main/java/com/sparta/harmony/order/exception/PaymentsNotFoundException.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- dto 이름 통일
- ExceptionHandler 위치 및 이름 변경
- SuccessHandler 위치 변경
- Config 클래스들 위치 변경
> [refactor]: dto 이름 통일, ExceptionHandler 위치 및 이름 변경, SuccessHandler 위치 변경, Config 클래스들 위치 변경

- src/main/java/com/sparta/harmony/common/handler/exception/GlobalExceptionHandler.java
- src/main/java/com/sparta/harmony/order/exception/OrderNotFoundException.java
- src/main/java/com/sparta/harmony/order/exception/PaymentsNotFoundException.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
[refactor]: 사용하지 않는 exception 제거 및 OrderService.java에서 exception 통일
> [refactor]: 사용하지 않는 exception 제거 및 OrderService.java에서 exception 통일

- src/main/java/com/sparta/harmony/common/logging/filter/ReqResLoggingFilter.java
- src/main/java/com/sparta/harmony/user/entity/Address.java
- src/main/resources/application.properties
- Security와 ReqResLoggingFilter.java 적상 작동을 위해 Security Filter 순서 조정.
- ReqResLoggingFilter.java 순서 최상위로 변경.
- 정상 작동 확인
> [refactor]: security와 logging 정상 작동을 위한 코드 refactor

- src/main/java/com/sparta/harmony/common/config/LoggingFilterConfig.java
- src/main/java/com/sparta/harmony/common/config/SecurityConfig.java
- src/main/java/com/sparta/harmony/common/logging/filter/ReqResLoggingFilter.java
- src/main/java/com/sparta/harmony/jwt/JwtUtil.java
- src/main/java/com/sparta/harmony/security/JwtAuthenticationFilter.java
- src/main/java/com/sparta/harmony/security/JwtAuthorizationFilter.java
- src/main/java/com/sparta/harmony/security/UserDetailsServiceImpl.java
- src/main/java/com/sparta/harmony/user/controller/UserController.java
- src/main/java/com/sparta/harmony/user/dto/LoginRequestDto.java
- src/main/java/com/sparta/harmony/user/repository/UserRepository.java
- src/main/java/com/sparta/harmony/user/service/UserService.java
- src/main/resources/application.properties
[feature]: security 로그인에서 email과 password를 받아오도록 설정.
- 토큰 header에 정상적으로 응답해주는것 확인. 
- ReqResLoggingFilter.java가 Security 전체 Filter들보다 먼저 작동하도록 설정
- #85
> [feature]: security 로그인에서 email과 password를 받아오도록 설정

- src/main/java/com/sparta/harmony/common/config/SecurityConfig.java
- src/main/java/com/sparta/harmony/common/handler/denied/CustomAccessDeniedHandler.java
- src/main/java/com/sparta/harmony/jwt/JwtUtil.java
- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/controller/PaymentsController.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- src/main/java/com/sparta/harmony/security/JwtAuthenticationFilter.java
- src/main/java/com/sparta/harmony/security/handler/loginfail/CustomLoginFailureHandler.java
- src/main/java/com/sparta/harmony/security/handler/loginsuccess/CustomLoginSuccessHandler.java
[feature]: 각 권한에 맞는 order controller 설정 완료. 
- 권한이 없을시 CustomAccessDeniedHandler.java를 통해 응답 전달
> [feature/order]: 각 권한에 맞는 order controller 설정 및 권한 없을 시의 handler 구현

- src/main/java/com/sparta/harmony/user/controller/UserController.java
- src/main/java/com/sparta/harmony/user/service/UserService.java
유저 controller 및 service에서 불필요한 코드 지움
> [refactor]: user login

- src/main/java/com/sparta/harmony/common/config/OpenApiConfig.java
- src/main/java/com/sparta/harmony/common/config/SecurityConfig.java
- src/main/java/com/sparta/harmony/common/dto/ApiPageResponseDto.java
- src/main/java/com/sparta/harmony/common/dto/ApiResponseDto.java
- src/main/java/com/sparta/harmony/common/handler/exception/RestApiException.java
- src/main/java/com/sparta/harmony/common/logging/filter/ReqResLoggingFilter.java
- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/controller/PaymentsController.java
- src/main/java/com/sparta/harmony/order/dto/OrderDetailResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderMenuListRequestDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderMenuListResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderRequestDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderResponsePageDto.java
- src/main/java/com/sparta/harmony/order/dto/OrderStatusRequestDto.java
- src/main/java/com/sparta/harmony/order/dto/PaymentsDetailResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/PaymentsResponseDto.java
- src/main/java/com/sparta/harmony/order/dto/PaymentsResponsePageDto.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- src/main/java/com/sparta/harmony/order/service/PaymentsService.java
- src/main/java/com/sparta/harmony/security/JwtAuthorizationFilter.java
- swagger 적용을 위한 security 수정.
- order domain swagger 적용.
#90
> [refactor]: swagger 적용을 위한 security 수정.

- src/main/java/com/sparta/harmony/HarmonyApplication.java
- src/main/java/com/sparta/harmony/common/config/JpaConfig.java
- src/main/java/com/sparta/harmony/common/config/UserAuditorAware.java
- postman으로 회원가입 시 SYSTEM 등록 확인.
- jwt로 api 주고 받을 시 DB에 해당 유저의 email 들어가는 것까지 확인
#92
> [feature]: 생성자, 수정자 자동 입력을 위한 AuditorAware 구현체 구현.

- src/main/java/com/sparta/harmony/common/dto/ApiPageResponseDto.java
- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/repository/OrderRepository.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- src/main/resources/logback-spring.xml
> [Hotfix]: logback 파일 경로 수정

- src/main/java/com/sparta/harmony/order/controller/OrderController.java
- src/main/java/com/sparta/harmony/order/controller/PaymentsController.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- src/main/java/com/sparta/harmony/order/service/PaymentsService.java
[refactor]: order domain swagger 수정.
> [refactor]: order domain swagger 수정.

- src/main/java/com/sparta/harmony/order/repository/OrderMenuRepository.java
- src/main/java/com/sparta/harmony/order/repository/PaymentsRepository.java
- src/main/java/com/sparta/harmony/order/service/OrderService.java
- src/main/java/com/sparta/harmony/order/service/PaymentsService.java
[refactor]: order domain의 soft delete와 payments 조회 오류 수정
#112
> [refactor]: order domain의 soft delete와 payments 조회 오류 수정
